apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-setosa
  namespace: shadow-ab
  labels:
    app: iris-setosa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-setosa
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-logistic
  namespace: shadow-ab
  labels:
    app: iris-logistic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-logistic
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: v1
kind: Service
metadata:
  name: iris
  namespace: shadow-ab
  labels:
    app: iris
spec:
  ports:
    - name: rest
      port: 5306
      protocol: TCP
  selector:
    app: iris

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: iris
  namespace: shadow-ab
spec:
  host: iris
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: setosa
      labels:
        version: setosa
    - name: logistic
      labels:
        version: logistic

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: iris
  namespace: shadow-ab
spec:
  hosts:
    - iris
  http:
    - route:
        - destination:
            host: iris
            subset: setosa
          weight: 100
      mirror:
        host: iris
        subset: logistic
      mirror_percent: 100