channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=24.0
- pip:
  - mlflow==2.12.1
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - protobuf==3.20.2
  - tensorflow-macos==2.13.0
  - tensorflow==2.13.0
name: mlflow-env
